services:
  rag_service:
    build:
      context: ./backend/rag_service_api
      dockerfile: Dockerfile  # Optional, but explicit
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile  # <== no path prefix like './frontend/app/...'
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://host.docker.internal:8000
    depends_on:
      - rag_service
    env_file:
      - .env
