version: 1.0.0
document_version: 2024-06-v1   # 🔁 Tracks version of indexed documents
logging_level: INFO               # 🪵 Controls pipeline logging (DEBUG, INFO, WARNING, etc.)
k: 5                              # 🔍 Top-K docs for retrieval

llm:
  provider: groq
  model: llama3-8b-8192
  temperature: 0.7                # 🌡️ LLM creativity level
  max_tokens: 512                 # ✂️ Max output length

prompt:
  format: json
  template: prompts/rag/json_prompts/rag_template_v1.json
  template_version: v1

vector_db:
  type: chroma
  persist_dir: data/vector_db
  collection_name: saviant_qa_v1
